loglevel: info
cpus: 1
monitoring:
  port: 5555
ssl:
  cert: "./mock-server/certs/server.cert"
  key: "./mock-server/certs/server.key"
protocols:
  http:
    enable: true
    mocks_dir: "./mock-server/mocks"
    port: 8081
  https:
    enable: false
    port: 8443
  http2:
    enable: false
    port: 8081
  ws:
    enable: false
    mocks_dir: "./mock-server/ws_mocks"
    port: 8082
  grpc:
    enable: false
    host: localhost
    port: 4312
    mocks_dir: "./mock-server/grpc/mocks"
    protos_dir: "./mock-server/grpc/protos"
backup:
  enable: true
  cron: "0 * * * *" # Hourly Backup
cache:
  enable: false
  ttl_seconds: 300
injection:
  enable: true
origins:
  - http://localhost:3000/
  - http://localhost:3001/
  - http://localhost:4200/
